# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    rebase-strategy: "auto"
    assignees:
      - "Zer0C0d3r"
    reviewers:
      - "Zer0C0d3r"
    labels:
      - "dependencies"
      - "performance"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    rebase-strategy: "auto"
    labels:
      - "dependencies"
